language: python
python:
  - "3.6"

sudo: required
dist: trusty

branches:
  only:
    - master
    - dev

install:
  - pip install -r requirements.txt
  # Install TeXLive
  - curl -sSL https://gist.githubusercontent.com/geosciman/b20ff2d856cfbc865689e57c06bb2e69/raw/install-tl.sh -o install-tl.sh
  - sudo bash install-tl.sh
  - source ~/.bash_profile
  - export TLMGR=`which tlmgr`
  # update texlive
  - sudo $TLMGR update --self --all -repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet/

script:
  - make html
  - make latexpdf

after_success:
  - cp build/latex/Geophysics.pdf build/html/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}   # 密码验证 https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
  local_dir: build/html
  on:
    branch: master

###############################################################################
# 若利用Travis CI自动发布在GitHub Pages上的静态网页，首先要成功生成，参考script.sh。
# 
# 参考: https://docs.travis-ci.com/user/deployment/pages/
# Deploying to GitHub Pages uses git push --force to overwrite the history on the 
# target branch, so make sure you only deploy to a branch used for that specific 
# purpose, such as gh-pages. It is possible to disable this “force push” behavior by 
# setting keep-history option to true.
# 
# Travis CI can deploy your static files to GitHub Pages after a successful build.
# 
# You will need to provide a personal access token and set the deployment provider 
# details in .travis.yml.
###############################################################################
